"""your message

Revision ID: 02abc71ed20b
Revises: 
Create Date: 2024-07-01 06:53:55.876204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02abc71ed20b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
