"""your message

Revision ID: 0c2d229164f5
Revises: f48d95094549
Create Date: 2024-07-06 14:26:40.927134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2d229164f5'
down_revision = 'f48d95094549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
